CREATE TABLE body_parts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE equipment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

CREATE TABLE exercises (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    difficulty text NOT NULL CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
    description text NOT NULL
);

CREATE TABLE exercise_body_parts (
    exercise_id bigint NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    body_part_id bigint NOT NULL REFERENCES body_parts(id) ON DELETE RESTRICT,
    PRIMARY KEY (exercise_id, body_part_id)
);

CREATE TABLE exercise_equipment (
    exercise_id bigint NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    equipment_id bigint NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT,
    PRIMARY KEY (exercise_id, equipment_id)
);

CREATE INDEX idx_exercises_difficulty ON exercises (difficulty);
CREATE INDEX idx_exercise_body_parts_body_part_id ON exercise_body_parts (body_part_id);
CREATE INDEX idx_exercise_equipment_equipment_id ON exercise_equipment (equipment_id);